FROM ubuntu:latest

ENV TZ=America/Chicago
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt update && apt upgrade -y && apt install -y \
        build-essential \
        clang \
        flex \
        bison \
        g++ \
        gawk \
        gcc-multilib \
        g++-multilib \
        gettext \
        git \
        libncurses5-dev \
        libssl-dev \
        python3-distutils \
        rsync \
        unzip \
        zlib1g-dev \
        file \
        wget

RUN useradd -m factory
USER factory
WORKDIR /home/factory
