FROM alpine:3.17

RUN apk --update --no-cache add bash nfs-utils libcap

# http://wiki.linux-nfs.org/wiki/index.php/Nfsv4_configuration
RUN rm -v /etc/idmapd.conf /etc/exports \
        && mkdir -p /var/lib/nfs/rpc_pipefs \
        && mkdir -p /var/lib/nfs/v4recovery \
        && printf '%s\n' \
        "rpc_pipefs /var/lib/nfs/rpc_pipefs rpc_pipefs  defaults 0 0" \
        "nfsd       /proc/fs/nfsd           nfsd        defaults 0 0" \
        >> /etc/fstab

EXPOSE 2049

# setup entrypoint
COPY ./entrypoint.sh /usr/local/bin
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
