###############################################################################
# NAME:             Containerfile
#
# AUTHOR:           Ethan D. Twardy <ethan.twardy@gmail.com>
#
# DESCRIPTION:      For building the compilations image.
#
# CREATED:          06/03/2022
#
# LAST EDITED:      06/21/2022
###

FROM docker.io/library/alpine:3.16

# Setup standard configuration
COPY configuration.yaml /usr/share/compilations/configuration.yaml

# Setup environment variables to direct the compilations application
ENV SECRET_FILE="/data/secret.yaml"
ENV CONF_FILE="/usr/share/compilations/configuration.yaml"

COPY compilations-entrypoint.sh /bin/entrypoint
ENTRYPOINT ["/bin/entrypoint"]

# Copy binary
ARG COMPILATIONS_PATH=./compilations-release
COPY $COMPILATIONS_PATH /bin/compilations

###############################################################################

