###############################################################################
# NAME:             Containerfile
#
# AUTHOR:           Ethan D. Twardy <ethan.twardy@gmail.com>
#
# DESCRIPTION:      For building the compilations image.
#
# CREATED:          06/03/2022
#
# LAST EDITED:      06/04/2022
###

FROM alpine:3.16

COPY build/compilations /bin/compilations

ENV SECRET_FILE="/data/secret_file.yaml"
ENV CONF_FILE="/data/conf_file.yaml"

COPY compilations-entrypoint.sh /bin/entrypoint
ENTRYPOINT ["/bin/entrypoint"]

###############################################################################

