FROM docker.io/jenkins/agent:latest

USER root
RUN apt-get update \
        && apt-get install -y --no-install-recommends \
        python3 \
        python3-pip \
        curl \
        procps \
        default-jre-headless \
        graphviz \
        plantuml \
        ruby-dev \
        && apt-get clean

# blog: PlantUML Setup
# The version installed by Debian is too old to recognize some of the keywords
# used in various blogposts.
ARG PLANTUML_VERSION=1.2023.13
ARG PLANTUML_DOWNLOAD=https://github.com/plantuml/plantuml/releases/download
RUN curl -L --output /usr/share/plantuml/plantuml.jar \
        ${PLANTUML_DOWNLOAD}/v${PLANTUML_VERSION}/plantuml-${PLANTUML_VERSION}.jar

# Install bundler
RUN gem install bundler

USER jenkins

# docs: Python/MkDocs setup
# TODO: Debian recently switched to enabling the "externally managed
# environment" feature of pip, which causes package installation to fail.
# But, I'm sure the versions in the Debian repositories are way too old,
# if they've even been packaged at all, so eventually I will need to switch
# to using virtual environments.
ENV PATH="/home/jenkins/.local/bin:$PATH"
RUN python3 -m pip install --break-system-packages setuptools wheel \
        && python3 -m pip install --break-system-packages mkdocs-material

# blog: When running "bundle install", install all gems to a user-owned
# location
RUN /bin/bash -l -c "bundle config set --local path $HOME/.gems"

COPY jenkins-agent-cmd.sh /bin/jenkins-agent-cmd
CMD ["/bin/jenkins-agent-cmd"]
