FROM docker.io/jenkins/agent:latest

USER root
RUN apt-get update \
        && apt-get install -y --no-install-recommends \
        python3 \
        python3-pip \
	xz-utils \
        && apt-get clean

# Create the nix store as writable by user jenkins
RUN install -d -m755 \
	-o $(awk -F: '/jenkins/{print $3}' /etc/passwd) \
	-g $(awk -F: '/jenkins/{print $4}' /etc/passwd) \
	/nix

USER jenkins

RUN bash -l -c "curl -L https://nixos.org/nix/install | sh"

# Setup for Nix on user jenkins' login shell and experimental features
RUN printf '%s\n' \
	'export USER=jenkins' \
	'source $HOME/.nix-profile/etc/profile.d/nix.sh' \
	>> $HOME/.bash_aliases \
	&& mkdir -p $HOME/.config/nix \
	&& echo 'experimental-features = nix-command flakes' \
	> $HOME/.config/nix/nix.conf

# Create a named volume for the nix store, for some amount of caching.
VOLUME /nix

# docs: Python/MkDocs setup
# TODO: Debian recently switched to enabling the "externally managed
# environment" feature of pip, which causes package installation to fail.
# But, I'm sure the versions in the Debian repositories are way too old,
# if they've even been packaged at all, so eventually I will need to switch
# to using virtual environments.
ENV PATH="/home/jenkins/.local/bin:$PATH"
RUN python3 -m pip install --break-system-packages setuptools wheel \
        && python3 -m pip install --break-system-packages mkdocs-material

COPY jenkins-agent-cmd.sh /bin/jenkins-agent-cmd
COPY flake-run.sh /bin/flake-run
CMD ["/bin/jenkins-agent-cmd"]
