FROM docker.io/jenkins/agent:latest

USER root
RUN apt-get update \
        && apt-get install -y --no-install-recommends \
        python3 \
        python3-pip \
        gnupg2 \
        curl \
        procps \
        plantuml \
        graphviz \
        && apt-get clean

# Install RVM with Ruby. See https://rvm.io/rvm/install
RUN gpg2 --recv-keys \
        409B6B1796C275462A1703113804BB82D39DC0E3 \
        7D2BAF1CF37B13E2069D6956105BD0E739499BDB \
        && (curl -sSL https://get.rvm.io | bash -s stable --ruby)

# Ruby/Jekyll setup (for blog)
RUN usermod -aG rvm jenkins
RUN /bin/bash -l -c ". /etc/profile.d/rvm.sh && gem install bundler"

USER jenkins

# Python/MkDocs setup:
#   1. Install dependencies of MkDocs
#   2. Create the volume mountpoint for deploying artifacts
ENV PATH="/home/jenkins/.local/bin:$PATH"
RUN python3 -m pip install setuptools wheel \
        && python3 -m pip install mkdocs-material \
        && mkdir /home/jenkins/repository
VOLUME /home/jenkins/repository

# RVM setup:
#   1. Perform environment setup for RVM while setting up a login shell
#   2. When running "bundle install", install all gems to a user-owned location
#   3. Create the mountpoint for deploying artifacts.
RUN echo ". /etc/profile.d/rvm.sh" >> $HOME/.bash_aliases \
        && /bin/bash -l -c "bundle config set --local path $HOME/.gems" \
        && mkdir /home/jenkins/blog
VOLUME /home/jenkins/blog

COPY jenkins-agent-cmd.sh /bin/jenkins-agent-cmd
CMD ["/bin/jenkins-agent-cmd"]
